In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from keras.optimizers import Adam,RMSprop,SGD,Adamax,Adagrad,Adadelta,Nadam
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import pickle

In [ ]:
df0 = pd.read_csv('original_data.csv')

In [ ]:
df0

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [ ]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    object
 9   Blood Pressure           374 non-null    object
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           374 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB

In [ ]:
df0.head(5)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [ ]:
df0.drop(['Person ID', 'Occupation','Quality of Sleep','Physical Activity Level','BMI Category','Sleep Disorder'], axis=1, inplace=True)

In [ ]:
df0.head()

,Gender,Age,Sleep Duration,Stress Level,Blood Pressure,Heart Rate,Daily Steps
0,Male,27,6.1,6,126/83,77,4200
1,Male,28,6.2,8,125/80,75,10000
2,Male,28,6.2,8,125/80,75,10000
3,Male,28,5.9,8,140/90,85,3000
4,Male,28,5.9,8,140/90,85,3000

In [ ]:
# Assuming 'gender' is a categorical variable that needs encoding
df0['Gender'] = df0['Gender'].map({'Male': 0, 'Female': 1})

In [ ]:
df0

,Gender,Age,Sleep Duration,Stress Level,Blood Pressure,Heart Rate,Daily Steps
0,0,27,6.1,6,126/83,77,4200
1,0,28,6.2,8,125/80,75,10000
2,0,28,6.2,8,125/80,75,10000
3,0,28,5.9,8,140/90,85,3000
4,0,28,5.9,8,140/90,85,3000
...,...,...,...,...,...,...,...
369,1,59,8.1,3,140/95,68,7000
370,1,59,8.0,3,140/95,68,7000
371,1,59,8.1,3,140/95,68,7000
372,1,59,8.1,3,140/95,68,7000
373,1,59,8.1,3,140/95,68,7000

In [ ]:
# Preprocess the 'Blood Pressure' column
df0[['Systolic', 'Diastolic']] = df0['Blood Pressure'].str.split('/', expand=True)
df0[['Systolic', 'Diastolic']] = df0[['Systolic', 'Diastolic']].astype(float)

# Drop the original 'Blood Pressure' column
df0.drop(columns=['Blood Pressure'], inplace=True)

In [ ]:
df0

,Gender,Age,Sleep Duration,Stress Level,Heart Rate,Daily Steps,Systolic,Diastolic
0,0,27,6.1,6,77,4200,126.0,83.0
1,0,28,6.2,8,75,10000,125.0,80.0
2,0,28,6.2,8,75,10000,125.0,80.0
3,0,28,5.9,8,85,3000,140.0,90.0
4,0,28,5.9,8,85,3000,140.0,90.0
...,...,...,...,...,...,...,...,...
369,1,59,8.1,3,68,7000,140.0,95.0
370,1,59,8.0,3,68,7000,140.0,95.0
371,1,59,8.1,3,68,7000,140.0,95.0
372,1,59,8.1,3,68,7000,140.0,95.0
373,1,59,8.1,3,68,7000,140.0,95.0

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# Assuming X contains the features (Age, Sleep Duration, Stress Level, Heart Rate, Daily Steps, Systolic, Diastolic)
numerical_features = ['Age', 'Sleep Duration', 'Stress Level', 'Heart Rate', 'Daily Steps', 'Systolic', 'Diastolic']

# Initialize MinMaxScaler
scaler = MinMaxScaler()

# Normalize the numerical features using MinMaxScaler
df0[numerical_features] = scaler.fit_transform(df0[numerical_features])

In [ ]:
df0

,Gender,Age,Sleep Duration,Stress Level,Heart Rate,Daily Steps,Systolic,Diastolic
0,0,0.00000,0.111111,0.6,0.571429,0.171429,0.407407,0.40
1,0,0.03125,0.148148,1.0,0.476190,1.000000,0.370370,0.25
2,0,0.03125,0.148148,1.0,0.476190,1.000000,0.370370,0.25
3,0,0.03125,0.037037,1.0,0.952381,0.000000,0.925926,0.75
4,0,0.03125,0.037037,1.0,0.952381,0.000000,0.925926,0.75
...,...,...,...,...,...,...,...,...
369,1,1.00000,0.851852,0.0,0.142857,0.571429,0.925926,1.00
370,1,1.00000,0.814815,0.0,0.142857,0.571429,0.925926,1.00
371,1,1.00000,0.851852,0.0,0.142857,0.571429,0.925926,1.00
372,1,1.00000,0.851852,0.0,0.142857,0.571429,0.925926,1.00
373,1,1.00000,0.851852,0.0,0.142857,0.571429,0.925926,1.00

In [ ]:
weights = {
    'Gender': 0.05,
    'Age': 0.1,
    'Sleep Duration': 0.2,
    'Stress Level': 0.15,
    'Heart Rate': 0.15,
    'Daily Steps': 0.1,
    'Systolic': 0.15,
    'Diastolic': 0.1
}

col= ['Gender','Age', 'Sleep Duration', 'Stress Level', 'Heart Rate', 'Daily Steps', 'Systolic', 'Diastolic']

In [ ]:
# Calculate the fitness score using the defined weights
df0['Fitness Score'] = df0[col].dot(pd.Series(weights))

In [ ]:
df0

,Gender,Age,Sleep Duration,Stress Level,Heart Rate,Daily Steps,Systolic,Diastolic,Fitness Score
0,0,27,6.1,6,77,4200,126.0,83.0,463.57
1,0,28,6.2,8,75,10000,125.0,80.0,1043.24
2,0,28,6.2,8,75,10000,125.0,80.0,1043.24
3,0,28,5.9,8,85,3000,140.0,90.0,347.93
4,0,28,5.9,8,85,3000,140.0,90.0,347.93
...,...,...,...,...,...,...,...,...,...
369,1,59,8.1,3,68,7000,140.0,95.0,748.72
370,1,59,8.0,3,68,7000,140.0,95.0,748.70
371,1,59,8.1,3,68,7000,140.0,95.0,748.72
372,1,59,8.1,3,68,7000,140.0,95.0,748.72
373,1,59,8.1,3,68,7000,140.0,95.0,748.72

In [ ]:
# Save the updated dataset with the fitness score
df0.to_csv('hv.csv', index=False)

#Gradient Boosting Regressor

In [ ]:
df = pd.read_csv('hv_data.csv')

In [ ]:
# Define the features (X) and the target variable (y)
X = df.drop(columns=['Fitness Score'])
y = df['Fitness Score']

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=28)

# Initialize the Gradient Boosting Regressor
gbr_regressor = GradientBoostingRegressor(n_estimators=1000, random_state=48)

# Train the model on the training data
gbr_regressor.fit(X_train, y_train)

# Make predictions on the test set
y_pred = gbr_regressor.predict(X_test)

In [ ]:
# Evaluate the model's performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)

print(f'Mean Squared Error: {mse}')
print(f'R-squared (R2) Score: {r2}')
print(f'Mean Absolute Error (MAE): {mae}')
print(f'Root Mean Squared Error (RMSE): {rmse}')

Mean Squared Error: 4.139163537054534e-05
R-squared (R2) Score: 0.9970496498853104
Mean Absolute Error (MAE): 0.0016263283833697847
Root Mean Squared Error (RMSE): 0.006433633139256958

In [ ]:
with open('techne_GBR.pkl', 'wb') as model_file:
    pickle.dump(gbr_regressor,model_file)
# gbr_regressor.save('techne_GBR.h5')

#ANN

In [ ]:
# Load the dataset
df = pd.read_csv('hv_data.csv')

In [ ]:
# Separate features and target variable
X = df.drop(columns=['Fitness Score'])
y = df['Fitness Score']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=28)

# # Preprocess categorical columns (like 'Gender') using one-hot encoding
# categorical_cols = ['Gender']
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), categorical_cols)], remainder='passthrough')
# X_train = ct.fit_transform(X_train)
# X_test = ct.transform(X_test)

# # Normalize the data
# scaler = MinMaxScaler()
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)

with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler,f)

# # Build the Neural Network model
# model = keras.Sequential([
#     keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
#     keras.layers.Dense(32, activation='relu'),
#     keras.layers.Dense(1)  # Output layer with a single neuron for regression
# ])
model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='linear'))


# Compile the model
optimizer = keras.optimizers.Nadam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='mse')

# Train the model
history = model.fit(X_train, y_train, epochs=180, batch_size=32, validation_split=0.2)

# Make predictions
y_pred = model.predict(X_test).flatten()

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f'Mean Squared Error: {mse}')
print(f'R-squared (R2) Score: {r2}')
print(f'Mean Absolute Error (MAE): {mae}')
print(f'Root Mean Squared Error (RMSE): {rmse}')

NameError: ignored

In [ ]:
# with open('techne_ANN.pkl', 'wb') as model_file:
#     pickle.dump(model,model_file)
model.save('techne_ANN.h5')

#END DEV COD

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Nadam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import pickle

# Load the dataset
df = pd.read_csv('hv.csv')

# Separate features and target variable
X = df.drop(columns=['Fitness Score'])
y = df['Fitness Score']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=28)

# Normalize the features
scaler_X = MinMaxScaler()
X_train_scaled = scaler_X.fit_transform(X_train)
X_test_scaled = scaler_X.transform(X_test)

# Normalize the target
scaler_y = MinMaxScaler()
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1))

# Build the Neural Network model
model = Sequential()
model.add(Dense(64, input_dim=X_train_scaled.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='linear'))

# Compile the model
optimizer = Nadam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='mse')

# Train the model
history = model.fit(X_train_scaled, y_train_scaled, epochs=180, batch_size=32, validation_split=0.1)

# Make predictions
X_test_scaled = scaler_X.transform(X_test)
y_pred_scaled = model.predict(X_test_scaled).flatten()

# Inverse transform to get values in the original range
y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1)).flatten()

# Calculate errors
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f'Mean Squared Error: {mse}')
print(f'R-squared (R2) Score: {r2}')
print(f'Mean Absolute Error (MAE): {mae}')
print(f'Root Mean Squared Error (RMSE): {rmse}')

# Save the trained model to an HDF5 file
model.save('techne_ANN.h5')

# Save the scalers to pickle files
with open('scaler_X.pkl', 'wb') as f:
    pickle.dump(scaler_X, f)

with open('scaler_y.pkl', 'wb') as f:
    pickle.dump(scaler_y, f)